package com.jadaptive.sslteam.cert.api.audit;

public enum CertificateAuditEventType {
    APPLICATION_CA_GENERATED,
    ROOT_KEY_EXPORT_ACKNOWLEDGED,
    APPLICATION_CA_SETUP_COMPLETED,
    APPLICATION_CA_SETUP_REJECTED,
    ROOT_CERTIFICATE_CREATED,
    ROOT_CERTIFICATE_RETIRED,
    ROOT_CERTIFICATE_REVOKED,
    CERTIFICATE_MATERIAL_DOWNLOADED,
    PRIVATE_KEY_DOWNLOADED,
    LEAF_ARTIFACT_DOWNLOADED,
    INTERMEDIATE_REQUEST_CREATED,
    INTERMEDIATE_REQUEST_EXPIRED,
    INTERMEDIATE_REQUEST_REJECTED,
    INTERMEDIATE_CERTIFICATE_IMPORTED,
    INTERMEDIATE_CERTIFICATE_RETIRED,
    INTERMEDIATE_CERTIFICATE_REVOKED,
    INTERMEDIATE_CERTIFICATE_REJECTED,
    LEAF_CERTIFICATE_ISSUED,
    LEAF_CERTIFICATE_REVOKED,
    LEAF_CERTIFICATE_REJECTED,
    LEAF_ATTENTION_UPDATED,
    KEY_CUSTODY_STORED,
    KEY_CUSTODY_READ_FAILED,
    KEY_CUSTODY_REJECTED
}
